// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    [Migration("20200612175457_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address");

                    b.Property<string>("Agency");

                    b.Property<bool>("Campsites");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("State");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            Address = "1 Zion Park Blvd,State Route 9,Springdale, UT 84767.",
                            Agency = "National Park Service",
                            Campsites = true,
                            Description = "Located in southern Utah near the city of Springdale. The park provides access to varied hiking, canyoneering, and water adventures.",
                            Name = "Zion",
                            State = "Utah"
                        },
                        new
                        {
                            ParkId = 2,
                            Address = "Grand Canyon, AZ 86023",
                            Agency = "National Park Service",
                            Campsites = true,
                            Description = "Truly grand: a steep-sided canyon carved by the Colorado River. The Grand Canyon features layered bands of red rock revealing millions of years of geological history. Viewpoints include Mather Point, Yavapai Observation Station and architect Mary Colter’s Lookout Studio and her Desert View Watchtower.",
                            Name = "Grand Canyon",
                            State = "Arizona"
                        },
                        new
                        {
                            ParkId = 3,
                            Address = "1675 Peter Iredale Rd, Hammond, OR 97121",
                            Agency = "Oregon State Parks",
                            Campsites = true,
                            Description = "Formerly the primary military defense  installation in the three-fort, Harbor Defense System at the mouth of the Columbia River. Now, Fort Stevens is a 4,300-acre park offering a variety of recreational opportunities, including camping, beach-combing, freshwater lake swimming, hiking trails, wildlife viewing and a historic shipwreck.",
                            Name = "Fort Stevens State Park",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 4,
                            Address = "Oregon 97750",
                            Agency = "National Park Service",
                            Campsites = false,
                            Description = "Part of the John Day Fossil Beds. The painted hills are located about 9 miles northwest of Mitchell, Oregon and distinguished by their stripes of red, tan, orange, and black. If you visit, stay off the dirt to help preserve the monument!",
                            Name = "Painted Hills",
                            State = "Oregon"
                        },
                        new
                        {
                            ParkId = 5,
                            Address = "3572 Olga Rd, Olga, WA 98279",
                            Agency = "Washington State Parks",
                            Campsites = true,
                            Description = "Public recreation area on Orcas Island in Puget Sound's San Juan Islands. This 5,424-acre park offers abundant camping (151 sites), five freshwater lakes for swimming and non-motorized boating, and more than 30 miles of hiking, bicycling, mountain biking and equestrian trails.",
                            Name = "Moran State Park",
                            State = "Washington"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
